### ISSUE TITLE
method not allowed

### ISSUE THREAD

**Issue by Serendipitya** [Nagi-ovo/Xuexin-Converter#13]
the method is not allowed for the requested URL

> 
<img width="901" alt="截屏2023-12-25 21 37 55" src="https://github.com/Nagi-ovo/CHSI-Converter/assets/48082533/e56a597a-0396-49af-af5f-4415978d8bcc">

**Comment by Nagi-ovo** [comment]
请检查是否有如下情况:

- 修改过下载后的报告文件名；
- 选择了错误的文件；
- 对文件做过任意修改。

这是否能解决你的问题？

**Comment by AstridTrj** [comment]
同样的问题，这和改文件名有啥关系呢？

**Comment by Nagi-ovo** [comment]
> 同样的问题，这和改文件名有啥关系呢？

有这样一个异常处理：

```python
if not file.filename.startswith('教育部学籍在线验证报告_'):
        flash('请不要传入无关文件')
        return redirect(request.url)
```

**Comment by AstridTrj** [comment]
啊这，好吧，这是没想到的。

**Comment by Nagi-ovo** [comment]
> 啊这，好吧，这是没想到的。

所以是这个问题吗🤔修改文件名后有没有得到解决呢

**Comment by AstridTrj** [comment]
> > 啊这，好吧，这是没想到的。
> 
> 所以是这个问题吗🤔修改文件名后有没有得到解决呢

是的，解决了，感谢感谢hhh

**Comment by Serendipitya** [comment]
就是文件名的问题，把代码拉下来看发现的



发自我的iPhone


------------------ Original ------------------
From: Jesse Zhang ***@***.***&gt;
Date: Thu,Dec 28,2023 3:40 PM
To: Nagi-ovo/CHSI-Converter ***@***.***&gt;
Cc: Renwei Peng ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Nagi-ovo/CHSI-Converter] method not allowed (Issue #13)





  
啊这，好吧，这是没想到的。
  
所以是这个问题吗🤔修改文件名后有没有得到解决呢

**Comment by Nagi-ovo** [comment]
感谢你们的反馈！
我现在就去完善一下相关的说明:)

**Comment by ETOgaosion** [comment]
现在学信网下下来的文件已经没有这种规律前缀了，来自mac safari，严格的check extendability有点差qaq

**Comment by Nagi-ovo** [comment]
> 现在学信网下下来的文件已经没有这种规律前缀了，来自mac safari，严格的check extendability有点差qaq

感谢反馈，已更新
