### ISSUE TITLE
选择文件后点击转换会报 405

### ISSUE THREAD

**Issue by Xguihur** [Nagi-ovo/Xuexin-Converter#14]
Method Not Allowed
The method is not allowed for the requested URL.

**Comment by Xguihur** [comment]
请问这个是我的操作问题吗？

**Comment by Nagi-ovo** [comment]
可能是因为修改过文件名。传入从学习网下载的原始文件肯定没有问题～发自我的荣耀手机-------- 原始邮件 --------发件人： Guihua Xu ***@***.***>日期： 2024年1月16日周二 上午11:20收件人： Nagi-ovo/CHSI-Converter ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [Nagi-ovo/CHSI-Converter] 选择文件后点击转换会报 405 (Issue #14)
请问这个是我的操作问题吗？

**Comment by Xguihur** [comment]
> 可能是因为修改过文件名。传入从学习网下载的原始文件肯定没有问题～发自我的荣耀手机-------- 原始邮件 --------发件人： Guihua Xu ***@***.***>日期： 2024年1月16日周二 上午11:20收件人： Nagi-ovo/CHSI-Converter ***@***.***>抄送： Subscribed ***@***.***>主 题： Re: [Nagi-ovo/CHSI-Converter] 选择文件后点击转换会报 405 (Issue #14) 请问这个是我的操作问题吗？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

我试了一下从学信网重新下载，能够传上去了，确实是这个问题
谢谢大佬
