### ISSUE TITLE
[Question] Converter 后的 docx 文档中部分中文内容未被转化

### ISSUE THREAD

**Issue by returnToInnocence** [Nagi-ovo/Xuexin-Converter#15]
> 首先，超级感谢您开源这个工具和对应详细的使用流程🙇‍

# Background

当我在跟着 readme 的教程下载好学信网的中文 pdf 以后，上传到了您给出的链接 http://www.ez4stu.nagi.fun/ 中，下载得到的 .docx 文件发现学校、班级、专业这几个内容没有成功翻译，如下部分内容
![image](https://github.com/Nagi-ovo/CHSI-Converter/assets/103014488/9cb711f1-c927-445a-96a3-90687c198b20)

请问这个应该如何解决呢

**Comment by Nagi-ovo** [comment]
> > 首先，超级感谢您开源这个工具和对应详细的使用流程🙇‍
> 
> # Background
> 当我在跟着 readme 的教程下载好学信网的中文 pdf 以后，上传到了您给出的链接 http://www.ez4stu.nagi.fun/ 中，下载得到的 .docx 文件发现学校、班级、专业这几个内容没有成功翻译，如下部分内容 ![image](https://private-user-images.githubusercontent.com/103014488/316222604-9cb711f1-c927-445a-96a3-90687c198b20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzc4ODksIm5iZiI6MTcxMTE3NzU4OSwicGF0aCI6Ii8xMDMwMTQ0ODgvMzE2MjIyNjA0LTljYjcxMWYxLWM5MjctNDQ1YS05NmEzLTkwNjg3YzE5OGIyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwNzA2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGM4NmM5MzFmZjM4MWU4YTJiZmE3Mzc5MzAzMmRjZWEwZWMyOGU2N2FkNjdlODdkZWYyNmMzMWZlNGJjYzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.irEpWcIm2Nd-63IBvgTIJy10eOYAGtoDguaIaX5RUx4)
> 
> 请问这个应该如何解决呢

因为出于隐私问题（其实不太会做也觉得没必要），所以这个小项目中并没有接入翻译接口，只是对于姓名等部分进行了简单的匹配替换，现在的结果是正常的🥲

**Comment by returnToInnocence** [comment]
> > > 首先，超级感谢您开源这个工具和对应详细的使用流程🙇‍
> > 
> > 
> > # Background
> > 当我在跟着 readme 的教程下载好学信网的中文 pdf 以后，上传到了您给出的链接 [http://www.ez4stu.nagi.fun](http://www.ez4stu.nagi.fun/) 中，下载得到的 .docx 文件发现学校、班级、专业这几个内容没有成功翻译，如下部分内容 ![image](https://private-user-images.githubusercontent.com/103014488/316222604-9cb711f1-c927-445a-96a3-90687c198b20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzc4ODksIm5iZiI6MTcxMTE3NzU4OSwicGF0aCI6Ii8xMDMwMTQ0ODgvMzE2MjIyNjA0LTljYjcxMWYxLWM5MjctNDQ1YS05NmEzLTkwNjg3YzE5OGIyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwNzA2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGM4NmM5MzFmZjM4MWU4YTJiZmE3Mzc5MzAzMmRjZWEwZWMyOGU2N2FkNjdlODdkZWYyNmMzMWZlNGJjYzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.irEpWcIm2Nd-63IBvgTIJy10eOYAGtoDguaIaX5RUx4)
> > 请问这个应该如何解决呢
> 
> 因为出于隐私问题（其实不太会做也觉得没必要），所以这个小项目中并没有接入翻译接口，只是对于姓名等部分进行了简单的匹配替换，现在的结果是正常的🥲

get！感谢您的回复！
