### ISSUE TITLE
没有识别到验证码

### ISSUE THREAD

**Issue by cute-omega** [Nagi-ovo/Xuexin-Converter#16]
不知为何，使用在线版的转换之后得到的英文版报告中丢失了在线验证码。
（顺便问一下，在之前的issue中有人提到了部分内容没有翻译为英文，想问一下这样部分没翻译的报告能过申请吗？）

**Comment by Nagi-ovo** [comment]
没有翻译的内容如“学校”等需要你自行翻译，验证码问题的话刚才测试了一下应该没有问题

**Comment by Nobodies123** [comment]
直接用部分翻译的报告，刚才申请通过了。验证码依旧没有显示在转换后的报告中，如图。
![1712302662031](https://github.com/Nagi-ovo/CHSI-Converter/assets/92797441/1ecfa16d-0d14-4670-a318-61245ca1168b)

**Comment by cute-omega** [comment]
拿着刚转换后的报告直接申请的，刚才验证通过了，可见报告部分不翻译也是可以的。但是验证码依旧没有显示在转换之后的报告中。
![1712302662031](https://github.com/Nagi-ovo/CHSI-Converter/assets/92797441/6a50218e-cc04-4df8-96d8-f83a057789e3)

**Comment by Nagi-ovo** [comment]
> 不好意思我理解错了哈，我以为是二维码这块的全部内容没有转换成功。

我没有做验证码转换的逻辑，当时实现上应该是遇到了一些问题。不过这点并不影响认证🥹

**Comment by cute-omega** [comment]
那好吧，反正我申请过了（感觉验证码也不需要转换的）
