### ISSUE TITLE
CHSI-Converter网页端失效

### ISSUE THREAD

**Issue by LinZiyuu** [Nagi-ovo/Xuexin-Converter#17]
返回405 Method Not Allow

**Comment by Nagi-ovo** [comment]
405 Method Not Allow 八成是因为你传入的档案是修改后的，去学习网重新下一份什么都不要改

**Comment by LinZiyuu** [comment]
感谢，发现不是文档修改的问题，可能是chrome的插件导致的，我换成Safari就可以了
