### ISSUE TITLE
GitHub Education验证条件越发严格

### ISSUE THREAD

**Issue by cute-omega** [Nagi-ovo/Xuexin-Converter#18]
现在需要学校名称能够匹配，所以需要手动把学校名改成英文。
同时还需要验证码（原文：If your document contains a verification code please make sure it is included in your image. If not, then please submit a different document in order to demonstrate your academic affiliation.），把中文验证码截图放上去。
如果提示没有日期，可能是毕业日期和右边花纹糊在一起看不出来了，手动把那里字号改小一号。
还要求姓名必须与GitHub的资料一致。
需要定位就不说了。
以及最讨厌的，现在几乎必须要求图片拍照上传，否则会被打回。姑且不说电脑摄像头有没有、能有多少像素。我就是拿OBS虚拟摄像头直接显示图片，GitHub居然还给我压画质然后说许多信息无法识别。我TM要吐了。（尝试把源图片改到1MB试试）

**Comment by Nagi-ovo** [comment]
可以重新组织一下你的需求嘛（我理解为需要加一些新功能？）

**Comment by cute-omega** [comment]
md申好几次没过脑子昏了，本来想说加一个校名翻译的，后来一想翻译的可能不对不如自己手改，现在看看就把新的要求写到readme里面算了

**Comment by Nagi-ovo** [comment]
> md申好几次没过脑子昏了，本来想说加一个校名翻译的，后来一想翻译的可能不对不如自己手改，现在看看就把新的要求写到readme里面算了

之前有考虑过做这个，不过觉得没法做好 corner case... 
btw 欢迎发一个文档的 PR！

**Comment by echo-ikun** [comment]
为什么会显示：“不要上传无关文件”

**Comment by cute-omega** [comment]
> 为什么会显示：“不要上传无关文件”

你要不发图片我也不知道为什么

**Comment by echo-ikun** [comment]
> > 为什么会显示：“不要上传无关文件”
> 
> 你要不发图片我也不知道为什么

<img width="744" alt="image" src="https://github.com/user-attachments/assets/8c63ce1d-a8c1-4eec-bdf8-c126d7126be4" />
如上图，放入学籍的pdf文件后报错

**Comment by cute-omega** [comment]
你确定你的pdf是直接从学信网下载的？没有编辑过？

> > > 为什么会显示：“不要上传无关文件”
> > 
> > 
> > 你要不发图片我也不知道为什么
> 
> <img alt="image" width="744" src="https://private-user-images.githubusercontent.com/127047807/397907645-8c63ce1d-a8c1-4eec-bdf8-c126d7126be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NjkxNjMsIm5iZiI6MTczNDc2ODg2MywicGF0aCI6Ii8xMjcwNDc4MDcvMzk3OTA3NjQ1LThjNjNjZTFkLWE4YzEtNGVlYy1iZGY4LWMxMjZkNzEyNmJlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQwODE0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWI5YTNlMDVhMjVjZDllYmU2MTlkZjVkZGRjMDViYzU3YWE2MjhhN2JhNTc3Y2QxMjM3ZTc5MTRjN2UzYjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.63gh7uci8BJjgwPQAWzX2h4QYILr-SQNR_YBQUFryd4"> 如上图，放入学籍的pdf文件后报错

**Comment by Nagi-ovo** [comment]
> > > 为什么会显示：“不要上传无关文件”
> > 
> > 
> > 你要不发图片我也不知道为什么
> 
> <img alt="image" width="744" src="https://private-user-images.githubusercontent.com/127047807/397907645-8c63ce1d-a8c1-4eec-bdf8-c126d7126be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg2ODQsIm5iZiI6MTczNDc4ODM4NCwicGF0aCI6Ii8xMjcwNDc4MDcvMzk3OTA3NjQ1LThjNjNjZTFkLWE4YzEtNGVlYy1iZGY4LWMxMjZkNzEyNmJlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxMzM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2QyNGFkNDFhOTE4YzE5ZjJjOTBmZmM1ZjI1YTk2ZWFmZGUwZTcyOGZjZmI1NDNjYjlmMzdiZTJlZWFmY2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._ADIgGlq1a1xvaMKGWd_qVziYImLoGx6lr3zfYtP4kE"> 如上图，放入学籍的pdf文件后报错

请参考 [Issue13](https://github.com/Nagi-ovo/CHSI-Converter/issues/13)
