### ISSUE TITLE
输出后排版建议：学校英文名称、姓名、拍摄屏幕、文件名

### ISSUE THREAD

**Issue by MitaraiOterai** [Nagi-ovo/Xuexin-Converter#19]
1. 学校英文名称，这个在之前的[issue](https://github.com/Nagi-ovo/CHSI-Converter/issues/18)里提到过，需要翻译成英文。
2. 直接上传学信网文件时会出现`Please select proof type 'Other' for this image.`的错误，参照[[知乎用户张周怡的方法](https://zhuanlan.zhihu.com/p/665726757)将文件名改成`Certification.jpg`可通过。
3. 直接上传word截图会出现`Please use your device camera to submit academic affiliation documents.`错误，解决方案：选择你的拍屏导师，使用手机拍照后修改大小上传。

> ~~因此学信网底纹可以去掉，因为某些指导中手写文件也可以。~~

4. 不要使用vpn，[认证网页](https://education.github.com/discount_requests/application)后把代理等关掉后刷新进入。
5. `You are unlikely to be verified until you have completed your with your full name exactly as it appears in your academic affiliation document. Please do not use a variation of your name or a nickname. Once you have updated your profile information log out and log back into GitHub before re-applying. ` 在修改个人姓名时，First Name 为名，Last Name 为姓，在自己的profile修改和[账单信息](https://github.com/settings/billing/payment_information)中请严格注意。此外，姓、名间需要加上空格。

**Comment by Nagi-ovo** [comment]
感谢，这几天生病了没来得及看。欢迎做一个readme的pr！
