### ISSUE TITLE
转换后空白内容

### ISSUE THREAD

**Issue by Tunglies** [Nagi-ovo/Xuexin-Converter#7]
使用在线网页和本地offline进行转换。中间信息区域全部为空格。
![QQ截图20231123100706](https://github.com/Nagi-ovo/CHSI-Converter/assets/77394545/172e93a5-c30a-4bba-93ac-eee6404fe649)

**Comment by Nagi-ovo** [comment]
这应该是缺少poppler服务的问题，我上服务器看眼

**Comment by Nagi-ovo** [comment]
刚检查过了docker image没有问题
关于`poppler`的需求我去修改一下文档，thanks anyway !

**Comment by Nagi-ovo** [comment]
可以提供下信息吗：
本地版本安装poppler后在线转换和桌面GUI版本是否还存在问题吗？
不胜感谢

**Comment by Tunglies** [comment]
> 可以提供下信息吗： 本地版本安装poppler后在线转换和桌面GUI版本是否还存在问题吗？ 不胜感谢

Windows 11 x64
Python 3.12.0
Pillow             10.1.0
PyPDF2             3.0.1
pypinyin           0.49.0

安装仅解决无法找到 poppler 问题。安装后仍无法正常工作。 转换出白，网页同样出白。

**Comment by Nagi-ovo** [comment]
> > 可以提供下信息吗： 本地版本安装poppler后在线转换和桌面GUI版本是否还存在问题吗？ 不胜感谢
> 
> Windows 11 x64 Python 3.12.0 Pillow 10.1.0 PyPDF2 3.0.1 pypinyin 0.49.0
> 
> 安装仅解决无法找到 poppler 问题。安装后仍无法正常工作。 转换出白，网页同样出白。

给你造成麻烦了，实在不好意思。请问：
1. 你是指[ez4stu.nagi.fun](ez4stu.nagi.fun)的转换仍然无法完成吗？
2. GUI版本在完成如下修改(#5 )后，仍然无法正常使用吗？

**Comment by EsunR** [comment]
是用的是 offline 分支吗，可以使用 master 的分支代码运行试试，或者直接根据 Dockerfile 构建镜像试试

**Comment by Tunglies** [comment]
> > > 可以提供下信息吗： 本地版本安装poppler后在线转换和桌面GUI版本是否还存在问题吗？ 不胜感谢
> > 
> > 
> > Windows 11 x64 Python 3.12.0 Pillow 10.1.0 PyPDF2 3.0.1 pypinyin 0.49.0
> > 安装仅解决无法找到 poppler 问题。安装后仍无法正常工作。 转换出白，网页同样出白。
> 
> 给你造成麻烦了，实在不好意思。请问：
> 
> 1. 你是指[ez4stu.nagi.fun](ez4stu.nagi.fun)的转换仍然无法完成吗？
> 2. GUI版本在完成如下修改([修复pypdf2报错 & 修复输出的Word文件只有姓名的问题 #5](https://github.com/Nagi-ovo/CHSI-Converter/pull/5) )后，仍然无法正常使用吗？

你好，是的。GUI 版本仍然无法使用。
```
PS D:\Github\CHSI-Converter> git branch
  master
* offline
PS D:\Github\CHSI-Converter> git log
commit d30a06fbf9c36bff118fc8b8a605568eebb
```
[ez4stu.nagi.fun](http://www.ez4stu.nagi.fun/) 也同样无法正常工作。

我试图从 master 构建 docker image. 同样地无法正常工作。

**Comment by Nagi-ovo** [comment]
> > > > 可以提供下信息吗： 本地版本安装poppler后在线转换和桌面GUI版本是否还存在问题吗？ 不胜感谢
> > > 
> > > 
> > > Windows 11 x64 Python 3.12.0 Pillow 10.1.0 PyPDF2 3.0.1 pypinyin 0.49.0
> > > 安装仅解决无法找到 poppler 问题。安装后仍无法正常工作。 转换出白，网页同样出白。
> > 
> > 
> > 给你造成麻烦了，实在不好意思。请问：
> > 
> > 1. 你是指[ez4stu.nagi.fun](ez4stu.nagi.fun)的转换仍然无法完成吗？
> > 2. GUI版本在完成如下修改([修复pypdf2报错 & 修复输出的Word文件只有姓名的问题 #5](https://github.com/Nagi-ovo/CHSI-Converter/pull/5) )后，仍然无法正常使用吗？
> 
> 你好，是的。GUI 版本仍然无法使用。
> 
> ```
> PS D:\Github\CHSI-Converter> git branch
>   master
> * offline
> PS D:\Github\CHSI-Converter> git log
> commit d30a06fbf9c36bff118fc8b8a605568eebb
> ```
> 
> [ez4stu.nagi.fun](http://www.ez4stu.nagi.fun/) 也同样无法正常工作。
> 
> 我试图从 master 构建 docker image. 同样地无法正常工作。

感谢反馈:)这两天抽时间排查一下问题~

**Comment by Nagi-ovo** [comment]
会不会是使用的黑色主题+黑色纸张导致的呢🤨
https://github.com/Nagi-ovo/CHSI-Converter/pull/5#issuecomment-1829653930

**Comment by Tunglies** [comment]
> 会不会是使用的黑色主题+黑色纸张导致的呢🤨 [#5 (comment)](https://github.com/Nagi-ovo/CHSI-Converter/pull/5#issuecomment-1829653930)

很奇妙的 BUG，使我的大脑旋转。Windows 改白色主题后程序正常使用了。

**Comment by Nagi-ovo** [comment]
> > 会不会是使用的黑色主题+黑色纸张导致的呢🤨 [#5 (comment)](https://github.com/Nagi-ovo/CHSI-Converter/pull/5#issuecomment-1829653930)
> 
> 很奇妙的 BUG，使我的大脑旋转。Windows 改白色主题后程序正常使用了。

哈哈哈是吧，我晚上一步步断点调试了十几分钟没查出问题，把生成文件的背景图一挪走发现黑纸白字在下面躺着好好的呢😂

**Comment by BenMake** [comment]
最新的word设置修改一下即可

<img width="596" alt="image" src="https://github.com/Nagi-ovo/CHSI-Converter/assets/1625218/beb30046-fd68-4133-9212-c675d548fd7f">
