### ISSUE TITLE
离线版点击转换无反应

### ISSUE THREAD

**Issue by seonwee** [Nagi-ovo/Xuexin-Converter#8]
![image](https://github.com/Nagi-ovo/CHSI-Converter/assets/61080587/e6641f5b-e67d-4b09-93d7-3dbaca866cc8)

**Comment by Nagi-ovo** [comment]
后台有报错吗？

**Comment by Tunglies** [comment]
> ![image](https://user-images.githubusercontent.com/61080587/285169708-e6641f5b-e67d-4b09-93d7-3dbaca866cc8.png)

应该是缺少 `poppler` 软件。

**Comment by Nagi-ovo** [comment]
> > ![image](https://user-images.githubusercontent.com/61080587/285169708-e6641f5b-e67d-4b09-93d7-3dbaca866cc8.png)
> 
> 应该是缺少 `poppler` 软件。

Windows系统可以在此下载[相关文件](https://github.com/oschwartz10612/poppler-windows/releases)，之后理应可以正常工作。

**Comment by seonwee** [comment]
> > > ![image](https://user-images.githubusercontent.com/61080587/285169708-e6641f5b-e67d-4b09-93d7-3dbaca866cc8.png)
> > 
> > 
> > 应该是缺少 `poppler` 软件。
> 
> Windows系统可以在此下载[相关文件](https://github.com/oschwartz10612/poppler-windows/releases)，之后理应可以正常工作。

你好，后台没有报错，我下载poppler后，将其中的bin目录添加到环境变量中后打开软件，点击转换还是没有反应。

**Comment by seonwee** [comment]
我本地部署项目可以成功使用了，谢谢。
